### ISSUE TITLE
OVS SDN control

### ISSUE THREAD

**Issue by GinesGarcia** [pa5h1nh0/GTP-U_OvS-kernel-extension#1]
Hi,
is it possible to pass these commands from an SDN controller?

thanks in advance,
Ginés

**Comment by pa5h1nh0** [comment]
You should extend the userspace daemon as well to make him understand the GTP tunnel. After that you should extend OpenFlow for specifying GTP commands, so that your SDN controller could use this extended version of OpenFlow.
I extended the OvS kernel module only.
