### ISSUE TITLE
Two short questions

### ISSUE THREAD

**Issue by mehrdadmoradi-crusoe** [pa5h1nh0/GTP-U_OvS-kernel-extension#5]
Hello,
I have two quick questions that will be appreciated if you can comment on them:

1. When I use  "ovs-dpctl add-gtpu-flow "gtp(teid=2064039937,dst=192.168.4.20)" "pop_gtp,2", I see that the destination mac address of the packet is set to a random number so the packet gets dropped by the next hop along the path. I try to  "pop_gtp,mod_dl_dst(08:00:27:15:b3:15),2" as the action but it seems this is not supported in the current implementation. Should I modify the code to get this done or I'm missing something?
2. When I set the tunnel id for the push operation 22814721 (ipv4(dst=192.168.3.100,frag=no), packets:25, bytes:2450, used:0.216s, actions:push_gtp(src=192.168.4.20,dst=192.168.4.90,teid=22814721),1
), I see the actual packets have this tunnel id 0X01205c01 or 18897921. What could cause this issue?

Thanks!

**Comment by pa5h1nh0** [comment]
1. This is actually very weird. I tested gtp encapsulation and decapsulation with a ton of use cases, and the dst MAC address was always properly set. This random thing shouldn't happen in principle by design. I explained this procedure as best as I could in section 4.3.3 of `Thesis.pdf`. You could assure yourself of this by analyzing `do_execute_actions()`, `push_gtpv1()`, `pop_gtpv1()`, `do_output()`, and `fill_ethdr()` functions.
2. That really shouldn't be a problem, you're apparently confused with the endianness, the byte order thingy. As you may know, the data (the packet headers at least) traveling through the network, by standard, are stored in network byte order (i.e. big endian). Indeed 22814721 in host byte order (i.e. little endian in this case) becomes 18897921 in big endian.

**Comment by mehrdadmoradi-crusoe** [comment]
Thanks for the comments!
1. I addressed the issue of mismatch between mac addresses by changing the mac address of my VM to the one used by pop_gtpv().
2. Actually, I might be wrong but it seems to me the issue is not with endianness. Let me describe why. I just verified that 22814721  (0x15C2001) is not the little endian representation of 18897921 (0x1205C01). Another thing is that when I capture the packets, I see Wireshark shows 0x01205c01 as the tunnel id while ./OVS-dpctl dump-flows returns 0x15c2001 as the tunnel id. We know that Wireshark automatically takes care of converting numbers to their proper host representation. This can indicate that the OVS actually has set the tunnel id to 0x1205C01 instead of 0x15C2001. It would be great if you can also comment on this.

**Comment by mehrdadmoradi-crusoe** [comment]
I was able to acquire correct packet traces between at my eNodeB. I have attached the expected and current tcpdump captures. If you take a look at the the packets from 192.168.5.200 to 192.168.3.100, you see that OVS-GTP sets the tunnel id to 0x1205C01 (although 0x15C2001 is requested) while the expected trace generated from real SGW correctly configures it 0x15C2001. 

[enb.zip](https://github.com/pa5h1nh0/GTP-U_OvS-kernel-extension/files/1383226/enb.zip)

**Comment by pa5h1nh0** [comment]
So, just to see if we're on the same page here, do you agree that the header values have to be converted from host byte order to network byte order? What I did is just using `htonl(value)`, if you execute `htonl(22814721)` it returns `18897921`.

**Comment by mehrdadmoradi-crusoe** [comment]
Technically, it should be converted to the host byte order. Also, you are right that htonl(22814721) returns 18897921. However, it seems that for tunnel id this conversion is not necessary at least for different GTP-enabled devices that I have in the lab. Once I remove htonl() in actions.c, all my problems get resolved and the host and server can communicate.

**Comment by pa5h1nh0** [comment]
Now that's the weirdest thing I heard from some time. I might think that your lab devices are little endian based architectures, so you expect to see and read little endian. Tell me if I'm wrong.

**Comment by mehrdadmoradi-crusoe** [comment]
Yes. You are right. That's weired..! Just to make it clear: I am using ip.access eNodeBs and OpenEPC RAN simulator. Both of them are the de facto software for LTE/EPC network prototyping.  Anyway, thanks for your quick answers..
